### ISSUE TITLE
Plugin "@netlify/plugin-functions-core" internal error: `Cannot find module`

### ISSUE THREAD

**Issue by asimkt** [netlify/zip-it-and-ship-it#114]
Had to manually install `node-fetch` to fix below build fail.
Build was failing with below log:

```
7:57:56 PM: Build ready to start
7:57:57 PM: build-image version: 30f629161c0736b1a3ecd8b418e5eeffab5c0faf
7:57:57 PM: build-image tag: v3.3.14
7:57:57 PM: buildbot version: 1da4cf38e1ad1fe9ce7deeeba939bcc9c6c3f794
7:57:58 PM: Fetching cached dependencies
7:57:58 PM: Starting to download cache of 133.8MB
7:58:03 PM: Finished downloading cache in 5.174276912s
7:58:03 PM: Starting to extract cache
7:58:09 PM: Finished extracting cache in 6.307184998s
7:58:10 PM: Finished fetching cache in 11.534513859s
7:58:10 PM: Starting to prepare the repo for build
7:58:10 PM: Preparing Git Reference refs/heads/master
7:58:12 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus 'build/' in the Netlify UI
7:58:12 PM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'functions' versus '' in the Netlify UI
7:58:12 PM: Creating functions prep folder
7:58:12 PM: Starting build script
7:58:12 PM: Installing dependencies
7:58:12 PM: Started restoring cached node version
7:58:16 PM: Finished restoring cached node version
7:58:17 PM: v10.20.1 is already installed.
7:58:18 PM: Now using node v10.20.1 (npm v6.14.4)
7:58:18 PM: Started restoring cached build plugins
7:58:18 PM: Finished restoring cached build plugins
7:58:18 PM: Attempting ruby version 2.6.2, read from environment
7:58:19 PM: Using ruby version 2.6.2
7:58:19 PM: Using PHP version 5.6
7:58:19 PM: 5.2 is already installed.
7:58:19 PM: Using Swift version 5.2
7:58:19 PM: Started restoring cached node modules
7:58:19 PM: Finished restoring cached node modules
7:58:19 PM: Started restoring cached yarn cache
7:58:19 PM: Finished restoring cached yarn cache
7:58:20 PM: Installing NPM modules using Yarn version 1.17.0
7:58:21 PM: yarn install v1.17.0
7:58:21 PM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
7:58:21 PM: [1/4] Resolving packages...
7:58:23 PM: [2/4] Fetching packages...
7:58:42 PM: info fsevents@2.1.2: The platform "linux" is incompatible with this module.
7:58:42 PM: info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
7:58:42 PM: info fsevents@1.2.11: The platform "linux" is incompatible with this module.
7:58:42 PM: info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
7:58:42 PM: [3/4] Linking dependencies...
7:58:42 PM: warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
7:58:42 PM: warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
7:58:42 PM: warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
7:58:42 PM: warning " > react-redux@7.2.0" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
7:58:42 PM: warning "react-scripts > eslint-config-react-app@5.2.0" has incorrect peer dependency "eslint-plugin-flowtype@3.x".
7:58:42 PM: warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
7:58:52 PM: [4/4] Building fresh packages...
7:58:54 PM: success Saved lockfile.
7:58:54 PM: Done in 33.45s.
7:58:54 PM: NPM modules installed using Yarn
7:58:55 PM: Started restoring cached go cache
7:58:55 PM: Finished restoring cached go cache
7:58:55 PM: go version go1.12 linux/amd64
7:58:55 PM: go version go1.12 linux/amd64
7:58:55 PM: Installing missing commands
7:58:55 PM: Verify run directory
7:58:57 PM: ​
7:58:57 PM: ┌─────────────────────────────┐
7:58:57 PM: │        Netlify Build        │
7:58:57 PM: └─────────────────────────────┘
7:58:57 PM: ​
7:58:57 PM: ❯ Version
7:58:57 PM:   @netlify/build 1.0.10
7:58:57 PM: ​
7:58:57 PM: ❯ Flags
7:58:57 PM:   mode: buildbot
7:58:57 PM: ​
7:58:57 PM: ❯ Current directory
7:58:57 PM:   /opt/build/repo
7:58:57 PM: ​
7:58:57 PM: ❯ Config file
7:58:57 PM:   /opt/build/repo/netlify.toml
7:58:57 PM: ​
7:58:57 PM: ❯ Context
7:58:57 PM:   production
7:58:57 PM: ​
7:58:57 PM: ❯ Loading plugins
7:58:57 PM:    - @netlify/plugin-functions-core@1.0.10 from core
7:58:58 PM: ​
7:58:58 PM: ┌────────────────────────────────────┐
7:58:58 PM: │ 1. build.command from netlify.toml │
7:58:58 PM: └────────────────────────────────────┘
7:58:58 PM: ​
7:58:58 PM: $ yarn build
7:58:58 PM: 
7:58:58 PM: 
7:58:58 PM: yarn run v1.17.0
7:58:58 PM: 
7:58:58 PM: $ react-scripts build
7:59:00 PM: Creating an optimized production build...
7:59:27 PM: Compiled with warnings.
7:59:27 PM: 
7:59:27 PM: ./src/components/molecules/dealerSelector/DealerSelector.js
7:59:27 PM:   Line 1:17:  'useState' is defined but never used  no-unused-vars
7:59:27 PM: ./src/api/utils.js
7:59:27 PM:   Line 21:5:  Unreachable code  no-unreachable
7:59:27 PM: ./src/features/product/Product.js
7:59:27 PM:   Line 2:8:  'isEmpty' is defined but never used  no-unused-vars
7:59:27 PM:   Line 7:8:  'car' is defined but never used      no-unused-vars
7:59:27 PM: ./src/components/molecules/colors/Colors.js
7:59:27 PM:   Line 3:8:   'Image' is defined but never used                                                                          no-unused-vars
7:59:27 PM:   Line 19:7:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
7:59:27 PM: Search for the keywords to learn more about each warning.
7:59:27 PM: To ignore, add // eslint-disable-next-line to the line before.
7:59:27 PM: File sizes after gzip:
7:59:27 PM:   84.6 KB   build/static/js/2.4ccc8e2e.chunk.js
7:59:27 PM:   23.67 KB  build/static/css/main.c8f91437.chunk.css
7:59:27 PM:   4.65 KB   build/static/js/main.d99b92a9.chunk.js
7:59:27 PM:   771 B     build/static/js/runtime-main.107bb8ca.js
7:59:27 PM: The project was built assuming it is hosted at /.
7:59:27 PM: You can control this with the homepage field in your package.json.
7:59:27 PM: The build folder is ready to be deployed.
7:59:27 PM: You may serve it with a static server:
7:59:27 PM:   yarn global add serve
7:59:27 PM:   serve -s build
7:59:27 PM: Find out more about deployment here:
7:59:27 PM:   bit.ly/CRA-deploy
7:59:27 PM: 
7:59:27 PM: Done in 29.03s.
7:59:27 PM: ​
7:59:27 PM: (build.command completed in 29.3s)
7:59:27 PM: ​
7:59:27 PM: ┌────────────────────────────────────────────────────────────┐
7:59:27 PM: │ 2. onPostBuild command from @netlify/plugin-functions-core │
7:59:27 PM: └────────────────────────────────────────────────────────────┘
7:59:27 PM: ​
7:59:27 PM: Packaging functions from functions
7:59:27 PM: ​
7:59:27 PM: ┌────────────────────────────────────────────────────────┐
7:59:27 PM: │ Plugin "@netlify/plugin-functions-core" internal error │
7:59:27 PM: └────────────────────────────────────────────────────────┘
7:59:27 PM: ​
7:59:27 PM:   Error message
7:59:27 PM:   Error: In file "/opt/build/repo/functions/api-server/api-server.js": Cannot find module 'node-fetch'
7:59:27 PM:   Require stack:
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/resolve.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/dependencies.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/node.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/main.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/netlify/src/deploy/hash-fns.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/netlify/src/deploy/index.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/netlify/src/index.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/api.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/load.js
7:59:27 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js
7:59:27 PM: ​
7:59:27 PM:   Plugin details
7:59:27 PM:   Package:        @netlify/plugin-functions-core
7:59:27 PM:   Version:        1.0.10
7:59:27 PM:   Repository:     git+https://github.com/netlify/build.git
7:59:27 PM:   npm link:       https://www.npmjs.com/package/@netlify/build
7:59:27 PM:   Report issues:  https://github.com/netlify/build/issues
7:59:27 PM: ​
7:59:27 PM:   Error location
7:59:27 PM:   In "onPostBuild" event in "@netlify/plugin-functions-core" from core
7:59:27 PM:       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
7:59:27 PM:       at Function.resolve (internal/modules/cjs/helpers.js:83:19)
7:59:27 PM:       at resolvePathFollowSymlinks (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/resolve.js:62:18)
7:59:27 PM:       at resolvePackageFallback (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/resolve.js:74:24)
7:59:27 PM:       at resolvePackage (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/resolve.js:33:27)
7:59:27 PM: ​
7:59:27 PM:   Error properties
7:59:27 PM:   { code: 'MODULE_NOT_FOUND' }
7:59:27 PM: ​
7:59:27 PM:   Resolved config
7:59:27 PM:   build:
7:59:27 PM:     command: yarn build
7:59:27 PM:     functions: /opt/build/repo/functions
7:59:27 PM:     publish: /opt/build/repo/build
7:59:27 PM:   redirects:
7:59:27 PM:     - from: /api/*
7:59:27 PM:       headers:
7:59:27 PM:         X-From: Netlify
7:59:27 PM:       status: 200
7:59:27 PM:       to: 'http://18.191.217.164/api_v1/:splat'
7:59:27 PM:     - from: /*
7:59:27 PM:       status: 200
7:59:27 PM:       to: /index.html
7:59:28 PM: Caching artifacts
7:59:28 PM: Started saving node modules
7:59:28 PM: Finished saving node modules
7:59:28 PM: Started saving build plugins
7:59:28 PM: Finished saving build plugins
7:59:28 PM: Started saving yarn cache
7:59:28 PM: Finished saving yarn cache
7:59:28 PM: Started saving pip cache
7:59:28 PM: Finished saving pip cache
7:59:28 PM: Started saving emacs cask dependencies
7:59:28 PM: Finished saving emacs cask dependencies
7:59:28 PM: Started saving maven dependencies
7:59:28 PM: Finished saving maven dependencies
7:59:28 PM: Started saving boot dependencies
7:59:28 PM: Finished saving boot dependencies
7:59:28 PM: Started saving go dependencies
7:59:28 PM: Finished saving go dependencies
7:59:28 PM: Error running command: Build script returned non-zero exit code: 1
7:59:28 PM: Failing build: Failed to build site
7:59:28 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
7:59:28 PM: Finished processing build request in 1m30.718117209s
```

**Comment by ehmicky** [comment]
Hi @asimkt,

To automatically install Netlify Functions dependencies, please add the following to your `netlify.toml`:

```
[[plugins]]
package = "@netlify/plugin-functions-install-core"
```

Alternatively, remove the `package.json` from the Functions directory and merge it to your project's top-level `package.json`. This solution results in faster builds as `npm install` (or `yarn`) will be called only once instead of twice. It also gives you more control on how the installation is happening, e.g. allowing you to add the `NPM_FLAGS`, `YARN_FLAGS`, `NPM_VERSION` and `YARN_VERSION` environment variables. Therefore, it is the recommended approach, although the alternative is supported as well.

**Comment by ehmicky** [comment]
Fixed by https://github.com/netlify/build/pull/1388

**Comment by asimqt** [comment]
> Hi @asimkt,
> 
> To automatically install Netlify Functions dependencies, please remove the `package.json` from the Functions directory and add the `dependencies` to your project's top-level `package.json` instead.
> 
> The following alternative is also supported: adding the following to your `netlify.toml`:
> 
> ```toml
> [[plugins]]
> package = "@netlify/plugin-functions-install-core"
> ```
> 
> However, beware that alternative:
> 
> * Results in slower builds as `npm install` (or `yarn`) will be called twice instead of once.
> * Does not currently give you much control over how the installation is happening, e.g. allowing you to add the `NPM_FLAGS`, `YARN_FLAGS`, `NPM_VERSION` and `YARN_VERSION` environment variables.

Isn't it easy for devs if Netlify automatically installs dependencies mentioned in the `functions/package.json`? 

I know this scenario is rare now, but some builds normally make a bundle of all dependencies together if they're using old task runners, right?

**Comment by asimqt** [comment]
I think Netlify is working on that :D https://community.netlify.com/t/how-to-include-dependencies-in-netlify-lambda-functions/2323/6

I think the best feature of Netlify as a company is not their advanced features, instead it is the effort you guys are putting to make millions of devs life easier.

**Comment by ehmicky** [comment]
Yes, absolutely @asimqt.
You can opt-in to that behavior using the `@netlify/plugin-functions-install-core` plugin as mentioned above.

**Comment by ldrummond** [comment]
Hi, I'm facing the same problem, but `@netlify/plugin-functions-install-core` is not fixing it. It works locally with `netlify dev` but on build, I am getting a `module not found` error. 

1. I have a function in the folder `functions/subscribe/` with the file `subscribe.js`. 
2. The function folder has a `package.json` file with relevant dependencies, and the `subscribe.js` file requires those dependencies at the top level. 
3. The top-level `package.json` file includes a script of `"postinstall": "netlify-lambda install"` and a dependency of `"netlify-lambda": "^1.6.3"`
4. The netlify.toml looks like this...

> [build]
>   publish = "dist"
>   functions = 'functions'
> [[redirects]]
>   from = "/api/*"
>   to = "/.netlify/functions/:splat"
>   status = 200
> [[plugins]]
>   package = "@netlify/plugin-functions-install-core"

Any tips would be greatly appreciated!

**Comment by ehmicky** [comment]
Hi @ldrummond,

Thanks for reaching out. Do you have a link to your deploy logs? Thanks!
