### ISSUE TITLE
ES6 Javascript functions are not working with esbuild

### ISSUE THREAD

**Issue by scottfwalter** [netlify/zip-it-and-ship-it#648]
Hi,

I converted a few functions to use the es6 syntax.  They run fine with "netlify dev" locally but when deployed they throw an error:

```
{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token 'export'","trace":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token 'export'","    at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)","    at internal/main/run_main_module.js:17:47"]}
```

Here is the function that fails:

```
export const handler = async (event, _context) => {
  const subject = event.queryStringParameters.name || 'World';

  try {
    return {
      statusCode: 200,
      body: JSON.stringify({
        message: `Hello ${subject}`
      })
    };
  } catch (error) {
    return { statusCode: 500, body: error.toString() };
  }
};
```

In my netlify.toml file I do specify esbuild:

```
[functions]
  directory = "functions"
  node_bundler = "esbuild"
```

I also have a Typescript function and it runs just fine both locally and deployed.

**Comment by eduardoboucas** [comment]
Hi @scottfwalter. Can you share more details about how you're deploying the project? Also, could you share a repository that I could use to reproduce?

I tried deploying your function, both using our CI flow and using the CLI, and it works (e.g. https://613f505ee920e0d022844961--eduardo-netlify-build-release-test.netlify.app/.netlify/functions/func1).

**Comment by scottfwalter** [comment]
Hi,

Here is my deployed demo site:  https://scottwalter.netlify.app/  and its repo:   https://github.com/scottfwalter/netlify-demo

I am using the Ubuntu Xenial 16.04 build image, but also tried Ubuntu Focal 20.04 with the same results.

**Comment by scottfwalter** [comment]
I removed everything from my netlify.toml and added items back in one and and time and found the culprit.  It's this plugin:

[[plugins]]
  package = "netlify-plugin-search-index"
  [plugins.inputs]
    exclude = ["/ignore-this-file.html", '''\/page\/''']

**Comment by eduardoboucas** [comment]
Thanks, @scottfwalter. That additional context was super helpful in pointing us to the right direction. It seems to be a problem with the plugin you mentioned. 

@ehmicky from our team has raised an issue in the plugin's repo. We can keep this one open until there's a resolution.

**Comment by scottfwalter** [comment]
It doesn't look like this plugin has been updated in about a year and a half.  In one of the issues listed on the plugin's repo, it looks like the maintainer is looking for someone else to take over the project.  

It's up to you if you want to keep the issue open or not.
